### ISSUE TITLE
Missing requirements.txt 

### ISSUE THREAD

**Issue by Sh0g0-1758** [ytingma/PPIDSG#1]
I tried to reproduce the results locally but was unable to do so as I got stuck in an endless loop of missing dependencies. Can the authors of the paper please push the same.

**Comment by ytingma** [comment]
About the requirement of python package, you can see the "Setup" of README.md. If you meet the missing of "dataset",  you can set the "downlaod=True" and set the correct save dataset directory ("data_dir") in the function of "get_dataset" in the './PPIDSG/utils.py'.

**Comment by Sh0g0-1758** [comment]
ah got it. Thanks a lot.
